name: web_scraping
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - beautifulsoup4=4.13.4=pyha770c72_0
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - catalogue=2.0.10=py312h7900ff3_1
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpathlib=0.21.1=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - confection=0.1.5=pyhecae5ae_0
  - curl=8.13.0=h332b0f4_0
  - cymem=2.0.11=py312h2ec8cdc_0
  - cython-blis=1.0.1=py312hc0a28a1_0
  - expat=2.7.0=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.13.3=ha770c72_1
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=10.4.0=h76408a6_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - jbig2dec=0.18=h267a509_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - langcodes=3.4.1=pyhd8ed1ab_1
  - language-data=1.3.0=pyhff2d567_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.83.1=hb768ceb_6
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.7.7=h75ea233_4
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libglib=2.84.0=h2ff4ddf_0
  - libgomp=15.1.0=h767d61c_2
  - libgumbo=1.0.0=h3f2d84a_1
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_1
  - liblzma-devel=5.8.1=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - marisa-trie=1.2.1=py312h2ec8cdc_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h178313f_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mupdf=1.25.2=py312h7f145e0_0
  - murmurhash=1.0.10=py312h2ec8cdc_2
  - ncurses=6.4=h6a678d5_0
  - nltk=3.9.1=pyhd8ed1ab_1
  - numpy=2.2.6=py312h72c5963_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py312hf9745cd_3
  - pcre2=10.44=hc749103_2
  - pip=25.1=pyhc872135_2
  - pixman=0.46.0=h29eaf8c_0
  - preshed=3.0.9=py312h2ec8cdc_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.4=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py312h680f630_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pymupdf=1.26.0=py312h64a381c_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=7_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py312h66e93f0_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - setuptools=78.1.1=py312h06a4308_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - smart-open=7.1.0=hd8ed1ab_0
  - smart_open=7.1.0=pyhd8ed1ab_0
  - soupsieve=2.7=pyhd8ed1ab_0
  - spacy=3.8.6=py312hc39e661_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - sqlite=3.45.2=h2c6b66d_0
  - srsly=2.5.1=py312h2ec8cdc_1
  - tesseract=5.5.0=ha6794fa_0
  - thinc=8.3.2=py312hc39e661_1
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typer=0.15.3=pyhf21524f_0
  - typer-slim=0.15.3=pyh29332c3_0
  - typer-slim-standard=0.15.3=h1a15894_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h04d1e81_0
  - ujson=5.10.0=py312h2ec8cdc_1
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wasabi=1.1.3=pyhd8ed1ab_1
  - weasel=0.4.1=pyhd8ed1ab_2
  - wheel=0.45.1=py312h06a4308_0
  - wrapt=1.17.2=py312h66e93f0_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_1
  - xz-gpl-tools=5.8.1=hbcc6ac9_1
  - xz-tools=5.8.1=hb9d3cd8_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py312h66e93f0_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - cryptography==45.0.3
      - pdfminer-six==20250327
      - pdfplumber==0.11.6
      - pillow==11.2.1
      - pypdfium2==4.30.1
prefix: /home/brice-nelson/miniconda3/envs/web_scraping
