name: jea_meeting_web_scraper
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12

  # Core science/utility
  - numpy
  - pandas
  - requests
  - beautifulsoup4
  - lxml
  - nltk
  - tqdm

  # NLP + spaCy
  - spacy
  - catalogue
  - cymem
  - preshed
  - thinc

  # PDF handling
  - pip
  - pip:
      - cryptography
      - pdfminer-six
      - pdfplumber
      - pillow
      - pypdfium2
